// Generated by IcedCoffeeScript 108.0.11

/*
* File: index
* User: Pu
* Date: 11/01/13
* Desc:
 */
var server, setting, web;

setting = require('./index-setting.json');

web = require('clc.foundation.web');

server = new web.Server(setting);

server.start();
