// Generated by IcedCoffeeScript 108.0.13
var web;

web = require('clc.foundation.web');

module.exports = function() {
  var development;
  development = new web.Development(this);
  return development.initialize();
};
