// Generated by IcedCoffeeScript 108.0.13

/*
* File: main
* User: Dow
* Date: 2014/10/24
 */
requirejs(['json!/datacenter/setting', 'materialize-css', 'threejs', 'angular', './app'], function(setting, M, THREE, angular, app) {
  window.setting = setting;
  window.THREE = THREE;
  return angular.bootstrap(document.documentElement, ['app']);
});
