// Generated by IcedCoffeeScript 108.0.13

/*
* File: routes
* User: Dow
* Date: 2014/10/24
 */
if (typeof define !== "function") { var define = require("amdefine")(module) };
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["clc.foundation.angular/router"], function(base) {
  var Router, exports;
  Router = (function(_super) {
    __extends(Router, _super);

    function Router($routeProvider) {
      Router.__super__.constructor.call(this, $routeProvider);
    }

    Router.prototype.start = function() {
      var namespace, _ref;
      namespace = (_ref = window.setting.namespace) != null ? _ref : "datacenter";
      this.routeTemplateUrl("/home", "/" + namespace + "/home/templates/index", "HomeController");
      this.routeTemplateUrl("/config", "/" + namespace + "/home/templates/config", "HomeController");
      namespace += "/portal";
      this.routeTemplateUrl("/login", "/" + namespace + "/templates/login", "LoginController");
      this.routeTemplateUrl("/users/:user", "/" + namespace + "/templates/user", "UserController");
      this.routeTemplateUrl("/401", "/" + namespace + "/templates/401", "MainController");
      this.routeTemplateUrl("/", "/" + namespace + "/templates/projects", "DatacenterController");
      this.routeTemplateUrl("/dispatch/:user/:project", "/" + namespace + "/templates/projects", "DispatchController");
      this.routeTemplateUrl("/projects", "/" + namespace + "/templates/projects", "ProjectsController");
      this.routeTemplateUrl("/project/:user/:project", "/" + namespace + "/templates/project", "ProjectController");
      this.routeTemplateUrl("/setting/:user/:project", "/" + namespace + "/templates/setting", "SettingController");
      this.routeTemplateUrl("/dashboard/:user/:project", "/" + namespace + "/templates/dashboard", "DashboardController");
      this.routeTemplateUrl("/capacity/:user/:project", "/" + namespace + "/templates/capacity", "CapacityController");
      this.routeTemplateUrl("/inventory/:user/:project", "/" + namespace + "/templates/inventory", "InventoryController");
      this.routeTemplateUrl("/capacity-2d/:user/:project", "/" + namespace + "/templates/capacity_2d", "Capacity2dController");
      this.routeTemplateUrl("/station-setting/:user/:project", "/" + namespace + "/templates/station_setting", "StationSettingController");
      this.routeTemplateUrl("/event-manager/:user/:project", "/" + namespace + "/templates/alarm", "AlarmController");
      this.routeTemplateUrl("/rack-plan/:user/:project", "/" + namespace + "/templates/rack_plan", "RackPlanController");
      this.routeTemplateUrl("/energy/:user/:project", "/" + namespace + "/templates/energy", "EnergyController");
      this.routeTemplateUrl("/video/:user/:project", "/" + namespace + "/templates/video", "VideoController");
      this.routeTemplateUrl("/monitoring/:user/:project", "/" + namespace + "/templates/monitoring", "MonitoringController");
      this.routeTemplateUrl("/door-manager/:user/:project", "/" + namespace + "/templates/door_manager", "DoorManagerController");
      this.routeTemplateUrl("/user-manager/:user/:project", "/" + namespace + "/templates/user_manager", "UserManagerController");
      this.routeTemplateUrl("/user-management/:user/:project", "/" + namespace + "/templates/user_management", "UserManagementController");
      this.routeTemplateUrl("/card-manage/:user/:project", "/" + namespace + "/templates/card_manage", "CardManageController");
      this.routeTemplateUrl("/distribute/:user/:project", "/" + namespace + "/templates/distribute", "DistributeController");
      this.routeTemplateUrl("/graphicac/:user/:project", "/" + namespace + "/templates/graphicac", "GraphicacController");
      this.routeTemplateUrl("/link/:user/:project", "/" + namespace + "/templates/link", "LinkController");
      this.routeTemplateUrl("/notification/:user/:project", "/" + namespace + "/templates/notification", "NotificationController");
      this.routeTemplateUrl("/asset-report/:user/:project", "/" + namespace + "/templates/asset_report", "AssetReportController");
      this.routeTemplateUrl("/user-info/:user/:project", "/" + namespace + "/templates/user_info", "UserInfoController");
      this.routeTemplateUrl("/alarm-report/:user/:project", "/" + namespace + "/templates/alarm_report", "AlarmReportController");
      this.routeTemplateUrl("/temperature-cloud/:user/:project", "/" + namespace + "/templates/temperature_cloud", "TemperatureCloudController");
      this.routeTemplateUrl("/inspect/:user/:project", "/" + namespace + "/templates/inspect", "InspectController");
      this.routeTemplateUrl("/job/:user/:project", "/" + namespace + "/templates/job", "JobController");
      this.routeTemplateUrl("/knowledge/:user/:project", "/" + namespace + "/templates/knowledge", "KnowledgeController");
      this.routeTemplateUrl("/schedule/:user/:project", "/" + namespace + "/templates/schedule", "ScheduleController");
      this.routeTemplateUrl("/log/:user/:project", "/" + namespace + "/templates/log", "LogController");
      this.routeTemplateUrl("/signal-report/:user/:project", "/" + namespace + "/templates/signal_report", "SignalReportController");
      this.routeTemplateUrl("/card-manager/:user/:project", "/" + namespace + "/templates/card_manager", "CardManagerController");
      this.routeTemplateUrl("/door-plan/:user/:project", "/" + namespace + "/templates/door_plan", "DoorPlanController");
      this.routeTemplateUrl("/video_histroy_list/:user/:project", "/" + namespace + "/templates/video_histroy_list", "Video_histroy_listController");
      this.routeTemplateUrl("/station-3d/:user/:project", "/" + namespace + "/templates/station_3d", "Station3dController");
      this.routeTemplateUrl("/alarm-setting/:user/:project", "/" + namespace + "/templates/alarm_setting", "AlarmSettingController");
      this.routeTemplateUrl("/mobile/:user/:project", "/" + namespace + "/templates/mobile", "MobileController");
      this.routeTemplateUrl("/jobs/:user/:project", "/" + namespace + "/templates/jobs", "JobsController");
      this.routeTemplateUrl("/door-report/:user/:project", "/" + namespace + "/templates/door_report", "DoorReportController");
      this.routeTemplateUrl("/video_reliable_list/:user/:project", "/" + namespace + "/templates/video_reliable_list", "Video_reliable_listController");
      this.routeTemplateUrl("/energy_flow/:user/:project", "/" + namespace + "/templates/energy_flow", "Energy_flowController");
      this.routeTemplateUrl("/work-overviewinfo/:user/:project", "/" + namespace + "/templates/work_overviewinfo", "WorkOverviewinfoController");
      this.routeTemplateUrl("/work-calendar/:user/:project", "/" + namespace + "/templates/work_calendar", "WorkCalendarController");
      this.routeTemplateUrl("/main-tasks/:user/:project", "/" + namespace + "/templates/main_tasks", "MainTasksController");
      this.routeTemplateUrl("/report-tasksum/:user/:project", "/" + namespace + "/templates/report_tasksum", "ReportTasksumController");
      this.routeTemplateUrl("/work-manager/:user/:project", "/" + namespace + "/templates/work_manager", "WorkManagerController");
      this.routeTemplateUrl("/electric-calendar/:user/:project", "/" + namespace + "/templates/electric_calendar", "ElectricCalendarController");
      this.routeTemplateUrl("/work-employee/:user/:project", "/" + namespace + "/templates/work_employee", "WorkEmployeeController");
      this.routeTemplateUrl("/report-frequencyevents/:user/:project", "/" + namespace + "/templates/report_frequencyevents", "ReportFrequencyeventsController");
      this.routeTemplateUrl("/record-hiscurve/:user/:project", "/" + namespace + "/templates/record_hiscurve", "RecordHiscurveController");
      this.routeTemplateUrl("/reporting-signal/:user/:project", "/" + namespace + "/templates/reporting_signal", "ReportingSignalController");
      this.routeTemplateUrl("/electricity-consumption/:user/:project", "/" + namespace + "/templates/electricity_consumption", "ElectricityConsumptionController");
      this.routeTemplateUrl("/report-activeevents/:user/:project", "/" + namespace + "/templates/report_activeevents", "ReportActiveeventsController");
      this.routeTemplateUrl("/finish-alarm/:user/:project", "/" + namespace + "/templates/finish_alarm", "FinishAlarmController");
      this.routeTemplateUrl("/battery-alarm/:user/:project", "/" + namespace + "/templates/battery_alarm", "BatteryAlarmController");
      this.routeTemplateUrl("/ups-alarm/:user/:project", "/" + namespace + "/templates/ups_alarm", "UpsAlarmController");
      this.routeTemplateUrl("/repord-report-alarm/:user/:project", "/" + namespace + "/templates/repord_report_alarm", "RepordReportAlarmController");
      this.routeTemplateUrl("/reporting/:user/:project", "/" + namespace + "/templates/reporting", "ReportingController");
      this.routeTemplateUrl("/ac-alarm/:user/:project", "/" + namespace + "/templates/ac_alarm", "AcAlarmController");
      this.routeTemplateUrl("/history-send-notification/:user/:project", "/" + namespace + "/templates/history_send_notification", "HistorySendNotificationController");
      this.routeTemplateUrl("/report-operations/:user/:project", "/" + namespace + "/templates/report_operations", "ReportOperationsController");
      this.routeTemplateUrl("/report-systemlog/:user/:project", "/" + namespace + "/templates/report_systemlog", "ReportSystemlogController");
      this.routeTemplateUrl("/temperature-cloud-2d/:user/:project", "/" + namespace + "/templates/temperature_cloud_2d", "TemperatureCloud2dController");
      this.routeTemplateUrl("/user-exclu/:user/:project", "/" + namespace + "/templates/user_exclu", "UserExcluController");
      this.routeTemplateUrl("/component-rolesrights/:user/:project", "/" + namespace + "/templates/component_rolesrights", "ComponentRolesrightsController");
      this.routeTemplateUrl("/temperature-cloud-3d/:user/:project", "/" + namespace + "/templates/temperature_cloud_3d", "TemperatureCloud3dController");
      this.routeTemplateUrl("/rack-stage-3d/:user/:project", "/" + namespace + "/templates/rack_stage_3d", "RackStage3dController");
      this.routeTemplateUrl("/temperature-cloud-history/:user/:project", "/" + namespace + "/templates/temperature_cloud_history", "TemperatureCloudHistoryController");
      this.routeTemplateUrl("/distribute-faultdrill/:user/:project", "/" + namespace + "/templates/distribute_faultdrill", "DistributefaultdrillController");
      this.routeTemplateUrl("/distribute-safe/:user/:project", "/" + namespace + "/templates/distribute_safe", "DistributesafeController");
      this.routeTemplateUrl("/ip-setting/:user/:project", "/" + namespace + "/templates/ip_setting", "IpSettingController");
      this.routeTemplateUrl("/equipments/:user/:project", "/" + namespace + "/templates/equipments", "EquipmentsController");
      this.routeTemplateUrl("/base-map-configuration/:user/:project", "/" + namespace + "/templates/base_map_configuration", "BaseMapConfigurationController");
      this.routeTemplateUrl("/batch-configuration/:user/:project", "/" + namespace + "/templates/batch_configuration", "BatchConfigurationController");
      this.routeTemplateUrl("/graphic-page/:user/:project", "/" + namespace + "/templates/graphic_page", "GraphicPageController");
      this.routeTemplateUrl("/historical-alarm/:user/:project", "/" + namespace + "/templates/historical_alarm", "HistoricalAlarmController");
      this.routeTemplateUrl("/signal-configuration/:user/:project", "/" + namespace + "/templates/signal_configuration", "SignalConfigurationController");
      this.routeTemplateUrl("/manage-data/:user/:project", "/" + namespace + "/templates/manage_data", "ManageDataController");
      this.routeTemplateUrl("/time-manage/:user/:project", "/" + namespace + "/templates/time_manage", "TimeManageController");
      this.routeTemplateUrl("/help-information/:user/:project", "/" + namespace + "/templates/help_information", "HelpInformationController");
      Router.__super__.start.apply(this, arguments);
      return this.routeTemplateUrl("/:key/:user/:project", "/" + namespace + "/templates/custom_dashboard", "DashboardController");
    };

    return Router;

  })(base.Router);
  return exports = {
    Router: Router
  };
});
