// Generated by IcedCoffeeScript 108.0.12

/*
* File: report-historysignal-directive
* User: David
* Date: 2019/01/03
* Desc:
 */
if (typeof define !== 'function') { var define = require('amdefine')(module) };
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['../base-directive', 'text!./style.css', 'text!./view.html', 'underscore', "moment"], function(base, css, view, _, moment) {
  var ReportHistorysignalDirective, exports;
  ReportHistorysignalDirective = (function(_super) {
    __extends(ReportHistorysignalDirective, _super);

    function ReportHistorysignalDirective($timeout, $window, $compile, $routeParams, commonService) {
      this.show = __bind(this.show, this);
      this.id = "report-historysignal";
      ReportHistorysignalDirective.__super__.constructor.call(this, $timeout, $window, $compile, $routeParams, commonService);
    }

    ReportHistorysignalDirective.prototype.setScope = function() {};

    ReportHistorysignalDirective.prototype.setCSS = function() {
      return css;
    };

    ReportHistorysignalDirective.prototype.setTemplate = function() {
      return view;
    };

    ReportHistorysignalDirective.prototype.show = function(scope, element, attrs) {
      var checkFilter, formatData, getEquipmentName, getSignalName, getStationName, getUnit, loadEquipmentAndSignals, _ref, _ref1;
      scope.multiflag = null;
      scope.view = false;
      scope.viewName = "报表11";
      scope.reportName = "";
      scope.selectSignals = [];
      scope.query = {
        startTime: '',
        endTime: ''
      };
      scope.headers = [
        {
          headerName: "序号",
          field: "index"
        }, {
          headerName: "项目名称",
          field: "stationName"
        }, {
          headerName: "设备名称",
          field: "equipmentName"
        }, {
          headerName: "数据名称",
          field: "signalName"
        }, {
          headerName: "数据值",
          field: "value"
        }, {
          headerName: "单位",
          field: "unitName"
        }, {
          headerName: "采集时间",
          field: "sampleTime"
        }
      ];
      scope.garddatas = [
        {
          index: "暂无数据",
          stationName: "暂无数据",
          equipmentName: "暂无数据",
          signalName: "",
          unitName: "",
          value: "",
          sampleTime: ""
        }
      ];
      scope.barlinevalue = [
        {
          name: "能耗信号1",
          key: '2016-01-01',
          value: 20,
          type: 'line'
        }, {
          name: "能耗信号1",
          key: '2016-01-02',
          value: 22,
          type: 'line'
        }, {
          name: "能耗信号3",
          key: '2016-01-01',
          value: 40,
          type: 'bar'
        }, {
          name: "能耗信号34",
          key: '2016-01-02',
          value: 42,
          type: 'bar'
        }
      ];
      scope.switchView = (function(_this) {
        return function() {
          scope.view = !scope.view;
          if (scope.view) {
            return scope.viewName = '图表';
          } else {
            return scope.viewName = '报表';
          }
        };
      })(this);
      scope.selectSignal = function(sig) {
        scope.selectSignals = [sig];
        scope.queryReport();
        return $('#mysigs').hide();
      };
      if ((_ref = scope.timeSubscription) != null) {
        _ref.dispose();
      }
      scope.timeSubscription = this.commonService.subscribeEventBus('time', (function(_this) {
        return function(d) {
          scope.query.startTime = moment(d.message.startTime).startOf('day');
          return scope.query.endTime = moment(d.message.endTime).endOf('day');
        };
      })(this));
      if ((_ref1 = scope.selectEquipSubscription) != null) {
        _ref1.dispose();
      }
      scope.selectEquipSubscription = this.commonService.subscribeEventBus('selectEquip', (function(_this) {
        return function(msg) {
          scope.multiflag = false;
          scope.selectedEquips = [msg.message];
          scope.selectedEquips = _.filter(scope.selectedEquips, function(item) {
            return item.level === 'equipment';
          });
          if (scope.parameters.type === "signal") {
            scope.reportName = "历史信号记录表";
          }
          return loadEquipmentAndSignals(scope.selectedEquips, function(data) {
            scope.selectSignals = [scope.signals[0]];
            if (scope.selectSignals.length) {
              return scope.queryReport();
            }
          });
        };
      })(this));
      scope.$watch('barlinevalue', (function(_this) {
        return function(value) {
          return _this.commonService.publishEventBus('barlinevalue', value);
        };
      })(this));
      loadEquipmentAndSignals = (function(_this) {
        return function(equipments, callback) {
          var equip, equipmentId, station, stationId, _i, _len, _results;
          scope.equipments = [];
          scope.signals = [];
          _results = [];
          for (_i = 0, _len = equipments.length; _i < _len; _i++) {
            equip = equipments[_i];
            if (equip.level === 'equipment') {
              stationId = equip.station;
              equipmentId = equip.id;
              _results.push((function() {
                var _j, _len1, _ref2, _results1;
                _ref2 = scope.project.stations.items;
                _results1 = [];
                for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
                  station = _ref2[_j];
                  if ((station != null ? station.model.station : void 0) === stationId) {
                    _results1.push(this.commonService.loadEquipmentById(station, equipmentId, (function(_this) {
                      return function(err, equipment) {
                        if (err) {
                          return console.log("err:", err);
                        }
                        scope.equipments.push(equipment);
                        return equipment.loadSignals(null, function(err, model) {
                          var finalData;
                          if (err) {
                            return console.log("err:", err);
                          }
                          finalData = _.uniq(model);
                          scope.signals = _.filter(finalData, function(sig) {
                            var _ref3;
                            return sig.model.visible === true && ((_ref3 = sig.model.dataType) === 'float' || _ref3 === 'int' || _ref3 === 'enum');
                          });
                          return typeof callback === "function" ? callback(true) : void 0;
                        });
                      };
                    })(this)));
                  } else {
                    _results1.push(void 0);
                  }
                }
                return _results1;
              }).call(_this));
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        };
      })(this);
      checkFilter = function() {
        if (!scope.selectedEquips || (!scope.selectedEquips.length)) {
          M.toast({
            html: '请选择设备'
          });
          return true;
        }
        if (moment(scope.query.startTime).isAfter(moment(scope.query.endTime))) {
          M.toast({
            html: '开始时间大于结束时间！'
          });
          return true;
        }
        return false;
      };
      scope.filterSig = (function(_this) {
        return function() {
          return function(equipment) {
            var _ref2;
            if ((_ref2 = equipment.model.dataType) === "int" || _ref2 === "float" || _ref2 === "enum" || _ref2 === "string") {
              return true;
            }
            return false;
          };
        };
      })(this);
      scope.queryReport = (function(_this) {
        return function(page, pageItems) {
          var data, filter, paging;
          if (page == null) {
            page = 1;
          }
          if (pageItems == null) {
            pageItems = scope.parameters.pageItems;
          }
          if (checkFilter()) {
            return;
          }
          if (scope.selectSignals[0]) {
            filter = {};
            filter["$or"] = _.map(scope.selectedEquips, function(equip) {
              return {
                station: equip.station,
                equipment: equip.id
              };
            });
            filter.startTime = scope.query.startTime;
            filter.endTime = scope.query.endTime;
            filter.user = scope.selectSignals[0].model.user;
            filter.project = scope.selectSignals[0].model.project;
            filter.signal = scope.selectSignals[0].model.signal;
            paging = {
              page: page,
              pageItems: pageItems
            };
            data = {
              filter: filter,
              sorting: {
                station: 1,
                equipment: 1,
                timestamp: 1
              }
            };
            return _this.commonService.reportingService.querySignalRecords(data, function(err, records, paging2) {
              var dataArray, pCount, _i, _ref2, _results;
              if (err) {
                return console.log('err:', err);
              }
              pCount = (paging2 != null ? paging2.pageCount : void 0) || 0;
              if (pCount <= 6) {
                if (paging2 != null) {
                  paging2.pages = (function() {
                    _results = [];
                    for (var _i = 1; 1 <= pCount ? _i <= pCount : _i >= pCount; 1 <= pCount ? _i++ : _i--){ _results.push(_i); }
                    return _results;
                  }).apply(this);
                }
              } else if (page > 3 && page < pCount - 2) {
                if (paging2 != null) {
                  paging2.pages = [1, page - 2, page - 1, page, page + 1, page + 2, pCount];
                }
              } else if (page <= 3) {
                if (paging2 != null) {
                  paging2.pages = [1, 2, 3, 4, 5, 6, pCount];
                }
              } else if (page >= pCount - 2) {
                if (paging2 != null) {
                  paging2.pages = [1, pCount - 5, pCount - 4, pCount - 3, pCount - 2, pCount - 1, pCount];
                }
              }
              scope.pagination = paging2;
              dataArray = records;
              if (!dataArray.length) {
                scope.barlinevalue = [];
                return scope.garddatas = [];
              } else {
                if ((_ref2 = dataArray[0].dataType) === 'int' || _ref2 === 'float' || _ref2 === 'enum') {
                  return formatData(dataArray, function(d) {
                    scope.garddatas = d;
                    scope.barlinevalue = _.map(scope.garddatas, function(item) {
                      var item2, _ref3;
                      return item2 = {
                        name: item.signalName,
                        key: item.sampleTime,
                        value: item.value,
                        type: ((_ref3 = scope.parameters) != null ? _ref3.chartType : void 0) || 'line',
                        unitName: item.unitName || ""
                      };
                    });
                    scope.barlinevalue = _.sortBy(scope.barlinevalue, 'key');
                    return scope.yname = scope.barlinevalue[0].unitName;
                  });
                } else {
                  return _this.display('此报表仅支持数字数据信号查询！', 500);
                }
              }
            });
          }
        };
      })(this);
      formatData = function(records, callback) {
        var finalData, index;
        finalData = null;
        index = 0;
        return finalData = _.map(records, (function(_this) {
          return function(record) {
            var _ref2;
            _.extend(record, {
              index: index + 1,
              unitName: getUnit(record.unit),
              stationName: getStationName(record.station),
              equipmentName: getEquipmentName(record.station + "." + record.equipment),
              value: (_ref2 = record.value) != null ? _ref2.toFixed(2) : void 0,
              signalName: getSignalName(record.signal),
              sampleTime: moment(record.timestamp).format("YYYY-MM-DD HH:mm:ss")
            });
            index++;
            if (index === records.length) {
              return typeof callback === "function" ? callback(records) : void 0;
            }
          };
        })(this));
      };
      scope.queryPage = function(page) {
        var paging;
        paging = scope.pagination;
        if (!paging) {
          return;
        }
        if (page === 'next') {
          page = paging.page + 1;
        } else if (page === 'previous') {
          page = paging.page - 1;
        }
        if (page > paging.pageCount || page < 1) {
          return;
        }
        if (scope.parameters.type === 'signal') {
          return scope.queryReport(page, paging.pageItems);
        } else if (scope.parameters.type === 'alarm') {
          return scope.queryAlarms(page, paging.pageItems);
        } else {
          return alert('err');
        }
      };
      getStationName = function(stationId) {
        var item, _i, _len, _ref2;
        _ref2 = scope.project.stations.items;
        for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
          item = _ref2[_i];
          if (item.model.station === stationId) {
            return item.model.name;
          }
        }
        return stationId;
      };
      getEquipmentName = function(equipmentId) {
        var item, tempEquipment, _i, _len, _ref2;
        tempEquipment = equipmentId.split('.');
        _ref2 = scope.equipments;
        for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
          item = _ref2[_i];
          if (item.model.equipment === tempEquipment[1] && item.model.station === tempEquipment[0]) {
            return item.model.name;
          }
        }
        return equipmentId;
      };
      getSignalName = function(signalId) {
        var item, _i, _len, _ref2;
        _ref2 = scope.signals;
        for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
          item = _ref2[_i];
          if (item.model.signal === signalId) {
            return item.model.name;
          }
        }
        return signalId;
      };
      getUnit = function(unitid) {
        var item, unitItem, _i, _len, _ref2, _ref3;
        if (!unitid) {
          return '';
        }
        _ref3 = (_ref2 = scope.project.dictionary) != null ? _ref2.signaltypes.items : void 0;
        for (_i = 0, _len = _ref3.length; _i < _len; _i++) {
          item = _ref3[_i];
          unitItem = item.model;
          if (unitItem.type === unitid) {
            return unitItem.unit;
          }
        }
        return unitid;
      };
      return scope.exportReport = (function(_this) {
        return function(header, garddatas, name) {
          var data, data2, reportName, wb, ws;
          if (garddatas[0].stationName === '暂无数据') {
            return _this.display("暂无数据，无法导出！");
          }
          data2 = _.map(garddatas, function(item) {
            return {
              "项目名称": item.stationName,
              "设备名称": item.equipmentName,
              "数据名称": item.signalName,
              "数据值": item.value,
              "单位": item.unitName,
              "采集时间": item.sampleTime
            };
          });
          data = data2;
          ws = XLSX.utils.json_to_sheet(data);
          wb = XLSX.utils.book_new();
          XLSX.utils.book_append_sheet(wb, ws, "Presidents");
          reportName = name + moment().format("YYYYMMDDHHmmss") + ".xlsx";
          return XLSX.writeFile(wb, reportName);
        };
      })(this);
    };

    ReportHistorysignalDirective.prototype.resize = function(scope) {};

    ReportHistorysignalDirective.prototype.dispose = function(scope) {
      var _ref, _ref1;
      if ((_ref = scope.timeSubscription) != null) {
        _ref.dispose();
      }
      return (_ref1 = scope.selectEquipSubscription) != null ? _ref1.dispose() : void 0;
    };

    return ReportHistorysignalDirective;

  })(base.BaseDirective);
  return exports = {
    ReportHistorysignalDirective: ReportHistorysignalDirective
  };
});
